title: Tyler Pease
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

style: light

plugins: 
  - jekyll-paginate
  - jekyll-octicons
  - jekyll-github-metadata

paginate: 5
paginate_path: "/blog/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - license
  - CNAME

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name