title: Tyler Pease
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

style: light

plugins: 
  - jekyll-paginate
  - jekyll-github-metadata

paginate: 5
paginate_path: "/blog/page:num/"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - license
  - CNAME