name: Tyler Pease
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
remote_theme: pages-themes/cayman@v0.2.0

style: light

plugins: 
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

paginate: 5
paginate_path: "/blog/page:num/"