name: Tyler Pease
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
remote_theme: pages-themes/cayman@v0.2.0

plugins: 
  - jekyll-paginate
  - jekyll-remote-theme

paginate: 5
paginate_path: "/blog/page:num/"