name: sitemap-generation
run-name: generating sitemap

on:
  push:
    branches:
      [ main ]
      
jobs:
  sitemap-job:
    runs-on: ubuntu-latest
    steps:
        - name: Examine the repo
          uses: actions/checkout@v2
          with:
              fetch-depth: 0
              
        - name: Generate sitemap
          id: sitemap
          uses: cicirello/generate-sitemap@v1.9.0
          with:
              base-url-path: https://www.peasetek.dev/
              drop-html-extension: true
          
        - name: Output stats
          run: |
              echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
              echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
              echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
              
        - name: Create pull request
          uses: peter-evans/create-pull-request@v3
          with:
            title: "Automated sitemap update"
            body: > 
              Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
              GitHub action. Automated pull-request generated by the 
              [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
